#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# hypr-effects.sh — shared kernel for the window-effect knobs
# (BarEditor → Hyprland tab and Window Controls, SUPER+SHIFT+B).
#
#   read                prints key=value with the LIVE values (hyprctl -j)
#   preview KEY=VAL ... updates the JSON state (source of truth) and applies
#                       those keys live with `hyprctl eval`. It does NOT touch
#                       the Lua overrides: Hyprland auto-reloads when a loaded
#                       config file changes, which is the visible "all windows
#                       restart" while dragging.
#   persist             regenerates config/window-effects.lua + config/gaps.lua
#                       from the JSON state (one Hyprland auto-reload).
#   apply KEY=VAL ...   preview + persist (CLI/manual use).
#
# State lives in config/window-effects.json and is seeded from the live values
# the first time. A partial change can never clobber the other knobs (the old
# bug: rewriting all 12 with misread gaps = reset).
#
# Environment:
#   HYPR_CONFIG_DIR  output directory (default ~/.config/hypr/config)
#   HYPR_NO_EVAL=1   do not call hyprctl (tests)
# ═══════════════════════════════════════════════════════════════════════════
set -u

CONF_DIR="${HYPR_CONFIG_DIR:-$HOME/.config/hypr/config}"
STATE="$CONF_DIR/window-effects.json"
mkdir -p "$CONF_DIR" || exit 1

# key · option · kind (float|int|cssgap|vec2x|vec2y)
SPECS=(
    "active_opacity decoration:active_opacity float"
    "inactive_opacity decoration:inactive_opacity float"
    "rounding decoration:rounding int"
    "blur_size decoration:blur:size int"
    "blur_passes decoration:blur:passes int"
    "gaps_in general:gaps_in cssgap"
    "gaps_out general:gaps_out cssgap"
    "border_size general:border_size int"
    "shadow_range decoration:shadow:range int"
    "shadow_render_power decoration:shadow:render_power int"
    "shadow_offset_x decoration:shadow:offset vec2x"
    "shadow_offset_y decoration:shadow:offset vec2y"
)

read_one() {
    local key="$1" opt="$2" kind="$3" json v
    json="$(hyprctl -j getoption "$opt" 2>/dev/null)" || return 0
    case "$kind" in
        float)  v="$(jq -r '.float // empty' <<<"$json")" ;;
        int)    v="$(jq -r '.int // empty' <<<"$json")" ;;
        # Hyprland 0.55+ returns "css gap data: 48 48 48 48" (.css field);
        # the UI is scalar, so take the first side.
        cssgap) v="$(jq -r '.css // empty' <<<"$json" | awk '{print $1}')" ;;
        vec2x)  v="$(jq -r '.vec2[0] // empty' <<<"$json")" ;;
        vec2y)  v="$(jq -r '.vec2[1] // empty' <<<"$json")" ;;
    esac
    if [[ -n "$v" && "$v" != "null" ]]; then
        printf '%s=%s\n' "$key" "$v"
    fi
}

cmd_read() {
    local spec
    for spec in "${SPECS[@]}"; do
        read_one $spec
    done
}

seed_state() {
    local json='{}' line k v tmp
    while IFS='=' read -r k v; do
        [[ -z "$k" ]] && continue
        json="$(jq -c --arg k "$k" --argjson v "$v" '. + {($k): $v}' <<<"$json")" || return 1
    done < <(cmd_read)
    tmp="$(mktemp "$CONF_DIR/.we-state.XXXXXX")" || return 1
    printf '%s\n' "$json" > "$tmp" && mv "$tmp" "$STATE"
}

# join with ", " (for the Lua snippets and tables)
join() { local IFS=', '; printf '%s' "$*"; }

write_lua() {
    local state="$1" tmp
    local ao io ro bs bp gr go bw sr sp ox oy
    ao="$(jq -r '.active_opacity // 0.85'       <<<"$state")"
    io="$(jq -r '.inactive_opacity // 0.80'     <<<"$state")"
    ro="$(jq -r '.rounding // 20'               <<<"$state")"
    bs="$(jq -r '.blur_size // 8'               <<<"$state")"
    bp="$(jq -r '.blur_passes // 3'             <<<"$state")"
    gr="$(jq -r '.gaps_in // 16'                <<<"$state")"
    go="$(jq -r '.gaps_out // 25'               <<<"$state")"
    bw="$(jq -r '.border_size // 2'             <<<"$state")"
    sr="$(jq -r '.shadow_range // 35'           <<<"$state")"
    sp="$(jq -r '.shadow_render_power // 5'     <<<"$state")"
    ox="$(jq -r '.shadow_offset_x // 0'         <<<"$state")"
    oy="$(jq -r '.shadow_offset_y // 10'        <<<"$state")"

    tmp="$(mktemp "$CONF_DIR/.we-lua.XXXXXX")" || return 1
    cat > "$tmp" <<LUA
-- Auto-generated by core/scripts/hypr-effects.sh — do not edit manually
hl.config({
    decoration = {
        active_opacity   = $ao,
        inactive_opacity = $io,
        rounding         = $ro,

        blur = {
            size   = $bs,
            passes = $bp,
        },

        shadow = {
            range        = $sr,
            render_power = $sp,
            offset       = { $ox, $oy },
        },
    },
})
LUA
    if command -v luac >/dev/null 2>&1 && ! luac -p "$tmp" >/dev/null 2>&1; then
        rm -f "$tmp"
        echo "error: window-effects.lua does not compile" >&2
        return 1
    fi
    mv "$tmp" "$CONF_DIR/window-effects.lua"

    tmp="$(mktemp "$CONF_DIR/.we-lua.XXXXXX")" || return 1
    cat > "$tmp" <<LUA
-- Auto-generated by core/scripts/hypr-effects.sh — do not edit manually
hl.config({
    general = {
        gaps_in     = $gr,
        gaps_out    = $go,
        border_size = $bw,
    },
})
LUA
    if command -v luac >/dev/null 2>&1 && ! luac -p "$tmp" >/dev/null 2>&1; then
        rm -f "$tmp"
        echo "error: gaps.lua does not compile" >&2
        return 1
    fi
    mv "$tmp" "$CONF_DIR/gaps.lua"
}

# Applies LIVE only the patched keys (hl.config merges partial tables:
# it does not touch the rest of general/decoration).
apply_live() {
    local state pair k v
    state="$(cat "$STATE")"
    local -A patch=()
    for pair in "$@"; do
        patch["${pair%%=*}"]="${pair#*=}"
    done

    local general=() dec=() blur=() shadow=()
    [[ -n "${patch[gaps_in]:-}"     ]] && general+=("gaps_in = ${patch[gaps_in]}")
    [[ -n "${patch[gaps_out]:-}"    ]] && general+=("gaps_out = ${patch[gaps_out]}")
    [[ -n "${patch[border_size]:-}" ]] && general+=("border_size = ${patch[border_size]}")

    [[ -n "${patch[active_opacity]:-}"   ]] && dec+=("active_opacity = ${patch[active_opacity]}")
    [[ -n "${patch[inactive_opacity]:-}" ]] && dec+=("inactive_opacity = ${patch[inactive_opacity]}")
    [[ -n "${patch[rounding]:-}"         ]] && dec+=("rounding = ${patch[rounding]}")
    [[ -n "${patch[blur_size]:-}"   ]] && blur+=("size = ${patch[blur_size]}")
    [[ -n "${patch[blur_passes]:-}" ]] && blur+=("passes = ${patch[blur_passes]}")
    [[ -n "${patch[shadow_range]:-}"        ]] && shadow+=("range = ${patch[shadow_range]}")
    [[ -n "${patch[shadow_render_power]:-}" ]] && shadow+=("render_power = ${patch[shadow_render_power]}")
    if [[ -n "${patch[shadow_offset_x]:-}" || -n "${patch[shadow_offset_y]:-}" ]]; then
        shadow+=("offset = { $(jq -r '.shadow_offset_x' <<<"$state"), $(jq -r '.shadow_offset_y' <<<"$state") }")
    fi

    local top=()
    [[ ${#general[@]} -gt 0 ]] && top+=("general = { $(join "${general[@]}") }")
    [[ ${#blur[@]}    -gt 0 ]] && dec+=("blur = { $(join "${blur[@]}") }")
    [[ ${#shadow[@]}  -gt 0 ]] && dec+=("shadow = { $(join "${shadow[@]}") }")
    [[ ${#dec[@]}     -gt 0 ]] && top+=("decoration = { $(join "${dec[@]}") }")
    [[ ${#top[@]} -eq 0 ]] && return 0

    hyprctl eval "hl.config({ $(join "${top[@]}") })" >/dev/null 2>&1
}

# Merge the given key=values into the JSON state and print the new state.
update_state() {
    [[ $# -eq 0 ]] && { cat "$STATE" 2>/dev/null || echo '{}'; return 0; }
    [[ -f "$STATE" ]] || seed_state
    local state pair k v
    state="$(cat "$STATE")"
    for pair in "$@"; do
        k="${pair%%=*}"
        v="${pair#*=}"
        state="$(jq -c --arg k "$k" --argjson v "$v" '.[$k] = $v' <<<"$state")" || return 1
    done
    printf '%s\n' "$state"
}

save_state() {
    local tmp
    tmp="$(mktemp "$CONF_DIR/.we-state.XXXXXX")" || return 1
    printf '%s\n' "$1" > "$tmp" && mv "$tmp" "$STATE"
}

cmd_preview() {
    [[ $# -eq 0 ]] && return 0
    local state
    state="$(update_state "$@")" || return 1
    save_state "$state" || return 1
    [[ "${HYPR_NO_EVAL:-0}" == "1" ]] || apply_live "$@"
    printf 'hypr-effects: previewed %s\n' "$*"
}

cmd_persist() {
    [[ -f "$STATE" ]] || seed_state
    write_lua "$(cat "$STATE")" || return 1
    # The two Lua writes can race Hyprland's auto-reload (it may read one file
    # before the other lands): re-apply the full state after writing so the
    # live values always match the JSON, whatever the reload read.
    if [[ "${HYPR_NO_EVAL:-0}" != "1" ]]; then
        local args=()
        while IFS= read -r kv; do args+=("$kv"); done < <(jq -r 'to_entries[] | "\(.key)=\(.value)"' "$STATE")
        apply_live "${args[@]}"
    fi
    printf 'hypr-effects: persisted\n'
}

cmd_apply() {
    cmd_preview "$@" || return 1
    cmd_persist
}

case "${1:-}" in
    read)    cmd_read ;;
    preview) shift; cmd_preview "$@" ;;
    persist) cmd_persist ;;
    apply)   shift; cmd_apply "$@" ;;
    *)       echo "usage: hypr-effects.sh read | preview KEY=VAL ... | persist | apply KEY=VAL ..." >&2; exit 1 ;;
esac
